### ISSUE TITLE
关于复杂度

### ISSUE THREAD

**Issue by haofeng0705** [ireneesun/MixSynthFormer#3]
文章说：the complexity of dot product self-attention calculations in transformers are quadratically proportional to the embedding size. 但是模型在 init 阶段通过插值的方式也转化成了 embedding（Those recovered poses are transformed into pose embeddings using linear projection and are fed into L blocks of MixSynthEncoder.）那这里无论采不采样输入的维度也没有实质减少呢？期待您的答复~

**Comment by ireneesun** [comment]
Hi haofeng0705, 模型里所有的pose（采样的和插值恢复的）都会转化成pose embedding，维度是由P到C。希望可以帮助到你

**Comment by haofeng0705** [comment]
@ireneesun thank you soooo much, i'm new to 3D HPE, this is a very good article, looking forward for the code ;)

**Comment by haofeng0705** [comment]
@ireneesun hi dear author, I would like to know if the MixSynth model proposed in this article can be used for pose lifting? Does this help reduce the complexity of the lifting model?

**Comment by ireneesun** [comment]
Hi @haofeng0705, you could try to apply a similar model structure for pose lifting. The synthetic attention could help to reduce the model complexity.
